name: Actualizar Bancos

on:
  schedule:
    # 0:01 AM hora de Bolivia (04:01 UTC)
    - cron: '1 4 * * *'
    # 7:01 AM hora de Bolivia (11:01 UTC)
    - cron: '1 11 * * *'
    # 12:01 PM hora de Bolivia (16:01 UTC)
    - cron: '1 16 * * *'
    # 16:01 PM hora de Bolivia (20:01 UTC)
    - cron: '1 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bancos:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias necesarias
        run: pip install requests pandas beautifulsoup4 urllib3

      - name: Ejecutar scraper de Banco Union
        continue-on-error: true
        run: python banco_union/scraper.py

      - name: Ejecutar scraper de BancoSol
        continue-on-error: true
        run: python bancosol/scraper.py

      - name: Ejecutar scraper de Baneco
        continue-on-error: true
        run: python baneco/scraper.py

      - name: Ejecutar scraper de BCO
        continue-on-error: true
        run: python bco/scraper.py

      - name: Ejecutar scraper de BCP
        continue-on-error: true
        run: python bcp/scraper.py

      - name: Ejecutar scraper de BISA
        continue-on-error: true
        run: python bisa/scraper.py

      - name: Ejecutar scraper de BMSC
        continue-on-error: true
        run: python bmsc/scraper.py

      - name: Ejecutar scraper de BNB
        continue-on-error: true
        run: python bnb/scraper.py

      - name: Ejecutar scraper de Ecofuturo
        continue-on-error: true
        run: python ecofuturo/scraper.py

      - name: Ejecutar scraper de FIE
        continue-on-error: true
        run: python fie/scraper.py

      - name: Ejecutar scraper de Fortaleza
        continue-on-error: true
        run: python fortaleza/scraper.py

      - name: Ejecutar scraper de Ganadero
        continue-on-error: true
        run: python ganadero/scraper.py

      - name: Ejecutar scraper de Prodem
        continue-on-error: true
        run: python prodem/scraper.py

      - name: Guardar datos de Bancos
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar Bancos" && git pull --rebase origin main && git push)





          
