name: Actualizar Binance

on:
  schedule:
    # "0 * * * *" significa "En el minuto cero de cada hora"
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-binance:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias necesarias
        run: pip install requests pandas beautifulsoup4 urllib3

      - name: Ejecutar scraper de Binance
        run: python binance/scraper.py

      - name: Guardar datos de Binance
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar Binance" && git pull --rebase origin main && git push)
