name: Actualizar todos los bancos, oficial y binance

on:
  schedule:
    # Se ejecuta automaticamente al minuto 0 de cada hora
    - cron: '0 * * * *'
  # Permite ejecutarlo a mano cuando desees
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias necesarias
        run: |
          pip install requests pandas beautifulsoup4

      - name: Ejecutar scraper de Binance
        run: |
          python binance/scraper.py

      - name: Ejecutar scraper de BCB Oficial
        run: |
          python oficial/scraper.py

      - name: Ejecutar scraper de BCP
        run: |
          python bcp/scraper.py

      - name: Ejecutar scraper de BNB
        run: |
          python bnb/scraper.py

      - name: Ejecutar scraper de Banco Union
        run: |
          python banco_union/scraper.py

      - name: Ejecutar scraper de Prodem
        run: |
          python prodem/scraper.py

      - name: Ejecutar scraper de BMSC
        run: |
          python bmsc/scraper.py

      - name: Ejecutar scraper de Baneco
        run: |
          python baneco/scraper.py

      - name: Ejecutar scraper de Ganadero
        run: |
          python ganadero/scraper.py

      - name: Ejecutar scraper de BISA
        run: |
          python bisa/scraper.py

      - name: Ejecutar scraper de BancoSol
        run: |
          python bancosol/scraper.py

      - name: Ejecutar scraper de Fortaleza
        run: |
          python fortaleza/scraper.py

      - name: Ejecutar scraper de FIE
        run: |
          python fie/scraper.py

      - name: Ejecutar scraper de Banco de la Comunidad
        run: |
          python bco/scraper.py

      - name: Ejecutar scraper de Ecofuturo
        run: |
          python ecofuturo/scraper.py

      - name: Guardar los archivos CSV en el repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add */*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualizar todas las cotizaciones" && git push)
